
export const AJAX_CALL_START = 'AJAX_CALL_START';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_VIDEOS_SUCCESS = 'LOAD_VIDEOS_SUCCESS';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
